version: "3"
services:
  backend:
    build:
      context: ./back_end_docker/  # Replace with the path to your backend Dockerfile and source code
    container_name: backend
    ports:
      - "3000:3000"
    

  frontend:
    build:
      context: ./front_end_docker/  # Replace with the path to your frontend Dockerfile and source code
    container_name: frontend
    ports:
      - "5173:5173"

networks:
  my-network:
