# Use the official MongoDB image as the base image
FROM mongo:latest


# Optionally, add custom configurations or scripts here
# Example:
# COPY ./my-mongodb-config-file.conf /etc/mongod.conf

# Expose the default MongoDB port (27017)
EXPOSE 27017

# Run the MongoDB server as the default command
CMD ["mongod"]